#!/usr/bin/env bash

law run PlotLikelihoodScan \
    --hh-model "$MODEL_BOOSTED_CLOSURE" \
    --version "$VERSION" \
    --datacards "$C4bcomb" \
    --pois C2V,CV \
    --scan-parameters C2V,-1,3,17:CV,-2,2,17 \
    --y-min -1 \
    --y-max 3 \
    --x-min -2 \
    --x-max 2 \
    --show-parameters kl,kt \
    --show-best-fit False \
    --show-box \
    --recompute-best-fit \
    --file-types "pdf,png" \
    --campaign run2 \
    --paper \
    --y-log \
    --unblinded True  \
    --show-significances 1,2,3,5 \
    --shift-negative-values \
    --LikelihoodScan-workflow "htcondor" \
    --LikelihoodScan-tasks-per-job 5 \
    --workers 4 \
    --use-snapshot True \
    --Snapshot-workflow "local" \
    --interpolation-method rbf \
    --interpolate-above 999 \
    --interpolate-nans \
    --remove-output 0,a,y
